### ISSUE TITLE
[Week 10] mid-v1.3

### ISSUE THREAD

**Issue by WeiTangLau** [CS2103-AY1819S2-T12-4/main#140]
We are required to do a proper release by mid-v1.3.

## mid-v1.3 Requirement
- Each PR also updates the relevant parts of documents and tests. This is to ensure that we do not pile up the documentation / testing work towards the end

### Product
Do a proper product release as described in the Developer Guide. You can name it something like v1.2.1. Ensure that the jar file works as expected by doing some manual testing. Reason: You are required to do a proper product release for v1.3. Doing a trial at this point will help you iron out any problems in advance. It may take additional effort to get the jar working especially if you use third party libraries or additional assets such as images.
- [x] Jar file is working

### Documentation
- [x] User Guide: Update where the document does not match the current product.

- [x] Developer Guide: Have a draft of the requirements of your project, as described in v1.2 progress guide.

**Comment by ptvrajsk** [comment]
Set out tasks completed. Refinements Carried out in v1.4
