### ISSUE TITLE
Update AutoTest 

### ISSUE THREAD

**Issue by WeiTangLau** [CS2103-AY1819S2-T12-4/main#28]
to test new features and regression testing

**Comment by ptvrajsk** [comment]
To close this issue, the following must be completed:
- [x] CommonsAutoTest
- [ ] LogicAutoTest
- [ ] ModelAutoTest
- [ ] StorageAutoTest
- [ ] TestUtilAutoTest
- [ ] UIAutoTest
- [ ] SystemAutoTest
- [ ] GUIAutoTest

**Comment by ptvrajsk** [comment]
~~Currently working on CommandsTests. (test.java.seedu.address.logic.commands)~~
~~It consists of the following JUnit Files:~~
~~AddCommandIntegrationTest~~
~~AddCommandTest~~
~~ClearCommandTest~~
~~CommandResultTest~~
~~DeleteCommandTest~~
~~EditCommandTest~~
~~EditPdfDescriptorTest~~
~~ExitCommandTest~~
~~FindCommandTest~~
~~HelpCommandTest~~
~~HistoryCommandTest~~
~~ListCommandTest~~
~~RedoCommandTest~~
~~SelectCommandTest~~
~~UndoCommandTest~~
~~CommandTestUtil~~

Irrelevant due to changes in project internals. Need to rework all tests.

**Comment by ptvrajsk** [comment]
Currently also working on CommonsTests. (test.java.seedu.address.commons)
It consists of the following JUnit Files:
- [x] IndexTest
- [x] ConfigTest
- [x] VersionTest
- [x] AppUtilTest
- [x] CollectionUtilTest
- [x] ConfigUtilTest
- [x] FileUtilTest
- [x] InvalidationListenerManagerTest
- [x] JsonUtilTest
- [x] StringUtilTest

**EDIT**: CommonsAutoTest Complete.

**Comment by WeiTangLau** [comment]
Due to a recent restructure of our code, we need to revamp all our test cases. Below are the list of tests I am currently working on

## Command Package
- [x] AddCommandIntegrationTest
- [x] AddCommandTest
- [x] ClearCommandTest
- [x] CommandResultTest
- [x] CommandTestUtil
- [ ] DeadlineCommandTest
- [ ] DecryptCommandTest
- [x] DeleteCommandTest
- [x] EditCommandTest
- [ ] EditPdfDescriptorTest
- [ ] EncryptCommandTest
- [ ] ExitCommandTest
- [ ] FindCommandTest
- [ ] HelpCommandTest
- [ ] HistoryCommandTest
- [ ] ListCommandTest
- [ ] MergeCommandTest
- [ ] RedoCommandTest
- [ ] SelectCommandTest
- [ ] TagCommandTest
- [ ] UndoCommandTest

## Command Parser Package
- [x] AddCommandParserTest
- [ ] PdfBookParserTest
- [ ] ArgumentTokenizerTest
- [ ] CommandParserTestUtil
- [ ] DeadlineCommandParserTest
- [x] DecryptCommandParserTest
- [x] DeleteCommandParserTest
- [x] EditCommandParserTest
- [ ] EncryptCommandParserTest
- [ ] FindCommandParserTest
- [ ] MergeCommandParserTest
- [ ] ParserUtilTest
- [ ] SelectCommandParserTest
- [ ] TagCommandParserTest

## Logic Test
- [ ] CommandHistoryTest
- [ ] LogicManagerTest

## Pdf Package
- [ ] DeadlineTest
- [ ] DirectoryTest
- [ ] NameContainsKeywordsPredicateTest
- [ ] NameTest
- [ ] PdfTest
- [ ] SizeTest
- [ ] UniquePdfListTest

**Comment by ptvrajsk** [comment]
Set out tasks for current milestone completed, updated list will be posted in v1.4 milestone.
