### ISSUE TITLE
[Week 3] Project Milestone: Institutionalization 

### ISSUE THREAD

**Issue by WeiTangLau** [CS2103-AY1819S2-T12-4/main#55]
### Understand AB4 code
- Read up on the code for AB4 to understand the features. 

### Have a rough idea for the project
- After understanding AB4's features, brainstorm ideas for the project.
- Deciding on whether to morph or optimise the project

**Comment by ptvrajsk** [comment]
# Project Meeting (31<sup>st</sup> January 2019)

## List of Ideas
### Morph
+ **Timetable Analyzer** : Store users weekly calendar schedule and help compare between users to highlight free periods common between users.
+ **Online Exam Paper Creator** : Create online exams that can be automatically graded upon completion.
+ **Code Snippet** : Cross-Directory code storage. Helps a user pull up snippet of code that he/she has typed previously.
+ **PDF++** : A PDF Manager that helps users keep track of all the PDFs within their computer and manipulate them with an array of features within one simple interface.

### Enhancement
+ **Address-book of Vendors** : Program that helps to track payments and the movements of goods between an Organization and its vendors.

## Conclusion
During the meeting, we had decided to morph the project after discussing a bunch of ideas for both enhancement and morphing. We now have a general consensus on the direction the project should move towards and the target audience this project is aimed at.

**Direction** : Morph
**Chosen Idea** : PDF++
