### ISSUE TITLE
[Week 5] Project Milestone: v1.0

### ISSUE THREAD

**Issue by WeiTangLau** [CS2103-AY1819S2-T12-4/main#57]
# Milestone v1.0

### Summary of Items

Milestone  | Work to be done
------------|---------
required documentations | a draft of v2.0 requirements
v2.0 conceptualised | a draft v2.0 user guide
feature releases planned | rough feature release plan

### Documenting User Guide
- [x] Draft a user guide for v2.0

### v1.0 Project Management
- [x] Assigning features to be done by v1.4
- Divide and document the features (from user stories and use cases) into incremental steps (v1.1, v1.2 and v1.3) assigned to the team members.

Attached PDF below:
[W05-T12-4.pdf](https://github.com/cs2103-ay1819s2-t12-4/main/files/2908365/W05-T12-4.pdf)

**Comment by ptvrajsk** [comment]
User guide & Feature assignment done on google doc. Refer to attached PDF above.

**Comment by ptvrajsk** [comment]
User stories and Use cases have been divided and assigned as issues to Milestone V1.1 for completion.
