### ISSUE TITLE
Good Commit Message Format

### ISSUE THREAD

**Issue by WeiTangLau** [CS2103-AY1819S2-T12-4/main#60]
Due to inconsistency faced for commit message while working on v1.0 & v1.1. We have decided to follow a standardised format. Please refer to [guideline](https://chris.beams.io/posts/git-commit/) here.

Attached a sample format below below:
![image](https://user-images.githubusercontent.com/42403590/53465415-c82f0a00-3a88-11e9-9433-48e13f9fb20a.png)

**Comment by lormee94** [comment]
![Alt Text](https://i.imgur.com/SiUHYul.gif)

##### LATB
