### ISSUE TITLE
[Week 7] Project Milestone V1.1

### ISSUE THREAD

**Issue by ptvrajsk** [CS2103-AY1819S2-T12-4/main#66]
### Completed at least 60% of Milestone v1.1 completion
The requirement stated that at least 60% completion for Milestone v1.1. However, we should aim for at least 80%
**Note: The project progress are tracked automatically, so do follow the instructions closely**

### Summary of Milestone v1.1
Milestone | Work to be done
----|----
Team Organisation / Repo | [Refer to website](https://github.com/cs2103-ay1819s2-t12-4/main/issues)
Code enhancement | created PRs to do local/global changes
Photo uploaded | Compliance with the [guideline]()
Project docs updated | updated docs are merged to master branch
Milestone wrapped up | a commit in master branch tagged as v1.1

**Note: Remember to tag the commit as v1.1**

#### v1.1 Documentation
Update 
- [x] User Guide
- [x] README
- [x] About Us  
- [x] Contact Us
- [x] Developer Guide 
**Submission: Merge your changes to the master branch of your repo. Create a PR with your changes.**

#### v1.1 Product
- [x] Each member to add some enhancements (local & global impact enhancements) in line with vision for v2.0 (Check the Milestone v1.1 for enhancements)

**Comment by ptvrajsk** [comment]
AboutUs, ContactUs and Individual changes to code base are completed. Refer to #70 for details.

**Comment by jetkan-yk** [comment]
User Guide on #74 
Local change on #75 
Global change on #76

**Comment by lormee94** [comment]
Local, Global change #77
